name: proxy_flutter
description: Anonymize Identity and Payments

version: 1.4.8+48

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.0
  intl_translation: ^0.17.7
  proxy_core:
    path: ../proxy-core-dart
    # git: git://github.com/yagnyam-in/proxy-core-dart.git
  proxy_messages:
    path: ../proxy-messages-dart
    # git: git://github.com/yagnyam-in/proxy-messages-dart.git
  json_annotation: ^3.0.0
  quiver: '>=2.0.0 <3.0.0'
  http: ^0.12.0+2
  logging: ^0.11.3+2
  uuid: ^2.0.2
  shared_preferences: ^0.5.3+4
  url_launcher: ^5.1.2
  flutter_slidable: ^0.5.3
  firebase_messaging: ^5.1.3
  google_sign_in: ^4.0.6
  firebase_auth: ^0.14.0+5
  firebase_crashlytics: ^0.1.0+3
  share: ^0.6.2+1
  firebase_dynamic_links: ^0.5.0+1
  cloud_firestore: ^0.12.9+3
  pointycastle: ^1.0.1
  asn1lib: ^0.5.8
  encrypt: ^3.2.0
  flutter_secure_storage: ^3.2.1+1
  rxdart: ^0.22.1+1
  package_info: ^0.4.0+6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.4.0
  json_serializable: ^3.0.0
  test: '>=0.12.42 <2.0.0'
  mockito: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/banks.png
    - assets/hotels.png
    - assets/key.png
    - assets/shopping_cart.png
    - assets/stores.png
    - assets/wallet.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


