name: proxy_flutter
description: App for anonymizing Identity and Payments

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:
  proxy_core:
    path: ../proxy-core-dart
    # git: git://github.com/yagnyam-in/proxy-core-dart.git
  proxy_messages:
    path: ../proxy-messages-dart
    # git: git://github.com/yagnyam-in/proxy-messages-dart.git
  json_annotation: ^2.0.0
  quiver: '>=2.0.0 <3.0.0'
  http: ^0.12.0
  logging: ^0.11.3+2
  uuid: ^2.0.0-rc1
  shared_preferences: ^0.4.3
  tuple: ^1.0.2
  url_launcher: ^5.0.1
  sqflite: ^1.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  test: '>=0.12.42 <2.0.0'
  mockito: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/banks.png
    - assets/hotels.png
    - assets/key.png
    - assets/shopping_cart.png
    - assets/stores.png
    - assets/wallet.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


